### ISSUE TITLE
Error with empty timeline

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/infodiversity-mock-social-media#67]
If I try to authenticate with my account `@glcdec`, which does not follow anybody, I get an error (see below). Before it used to show a message saying empty timeline.

```
Connect
500 TypeError: /home/ubuntu/Truman/views/script.pug:41
   39|    
   40|     -var ii = 0;
 > 41|     input(type='hidden', id='session_input', name=script[0].session_id, value=_csrf)
   42|     each val in script
   43|       -ii = ii + 1
   44|       -console.log(ii)
Cannot read property 'session_id' of undefined
   at eval (eval at wrap (/home/ubuntu/Truman/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:700:107)
   at template (eval at wrap (/home/ubuntu/Truman/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1493:120)
   at Object.exports.renderFile (/home/ubuntu/Truman/node_modules/pug/lib/index.js:427:38)
   at Object.exports.renderFile (/home/ubuntu/Truman/node_modules/pug/lib/index.js:417:21)
   at View.exports.__express [as engine] (/home/ubuntu/Truman/node_modules/pug/lib/index.js:464:11)
   at View.render (/home/ubuntu/Truman/node_modules/express/lib/view.js:135:8)
   at tryRender (/home/ubuntu/Truman/node_modules/express/lib/application.js:640:10)
   at Function.render (/home/ubuntu/Truman/node_modules/express/lib/application.js:592:3)
   at ServerResponse.render (/home/ubuntu/Truman/node_modules/express/lib/response.js:1012:7)
   at ServerResponse.res.render (/home/ubuntu/Truman/node_modules/express-flash/lib/express-flash.js:29:16)
   at axx.get.then (/home/ubuntu/Truman/controllers/script.js:96:19)
   at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by glciampaglia** [comment]
Duplicate of #56, closing.
